# See https://github.com/conda-forge/maturin-feedstock/pull/120
cxx_compiler:          # [win]
  - vs2022             # [win]
cxx_compiler_version:  # [win]
  - 19.40              # [win]
rust_compiler_version:
  - "1.74"
