{% set name = "maturin" %}
{% set version = "0.15.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 247bec13d82021972e5cb4eb38e7a7aea0e7a034beab60f0e0464ffe7423f24b

build:
  number: 0
  skip: true  # [py==27]
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('rust') }}
    - openssl                          # [unix]
  host:
    - pip
    - setuptools-rust
    - wheel
    - python
    - tomli >=1.1.0
    - openssl                          # [unix]
  run:
    - python
    - tomli >=1.1.0

test:
  commands:
    - maturin --help

about:
  home: https://github.com/PyO3/maturin
  license: MIT
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages

extra:
  recipe-maintainers:
    - messense
    - apcamargo
    - synapticarbors
