{% set name = "maturin" %}
{% set version = "1.7.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05ccbdfe96ad58d70dba9c3eed090726db8ccbaf07ec03852113ca2fec6d84b

build:
  number: 0
  skip: true  # [py==27]
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - openssl                          # [unix]
    - pkg-config                       # [unix]
  host:
    - pip
    - setuptools
    - setuptools-rust >=1.4.0
    - wheel
    - python
    - tomli >=1.1.0
    - openssl                          # [unix]
  run:
    - python
    - tomli >=1.1.0

test:
  commands:
    - maturin --help

about:
  home: https://github.com/PyO3/maturin
  license: MIT
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages

extra:
  recipe-maintainers:
    - messense
    - apcamargo
    - synapticarbors
