{% set name = "maturin" %}
{% set version = "1.3.1" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: efa194e99ae5fff185263d8244acacb12ae256ea73aba62c9446f6075ffc7ac1
  patches:  # [s390x]
    # ring adds big endian support from 0.17 only
    - patches/0001-ring-0.17.3-for-s390x.patch # [s390x]

build:
  number: 0
  skip: True  # [py<37]

requirements: # [s390x]
  build:      # [s390x]
    - patch   # [s390x]


outputs:
  - name: {{ name }}
    script: bld-win.bat                  # [win]
    script: build-unix.sh                # [not win]
    missing_dso_whitelist:   # [osx]
      - /usr/lib/libresolv.9.dylib  # [osx]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('rust') }}     # [not win]
        - rust_win-64                # [win]
      host:
        - pip
        - python
        - setuptools
        - setuptools-rust
        - wheel
        - tomli >=1.1.0               # [py<311]
      run:
        - python
        - tomli >=1.1.0               # [py<311]
    test:
      imports:
        - maturin
      requires:
        - pip
      commands:
        - maturin -V
        - maturin --help
        - maturin build --help
        - pip check

  - name: {{ name }}-gnu
    script: bld-win.bat
    build:
      skip: true  # [not win]
    requirements:
      build:
        - {{ compiler('m2w64_c') }}
        - rust-gnu_win-64
      host:
        - pip
        - python
        - setuptools
        - setuptools-rust
        - wheel
        - tomli >=1.1.0                # [py<311]
      run:
        - python
        - tomli >=1.1.0                # [py<311]
    test:
      imports:
        - maturin
      requires:
        - pip
      commands:
        - maturin -V
        - maturin --help
        - maturin build --help
        - pip check

about:
  home: https://www.maturin.rs/
  license: MIT OR Apache-2.0
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  description: |
    This project is meant as a zero configuration replacement for setuptools-rust and milksnake.
    It supports building wheels for python 3.5+ on windows, linux, mac and freebsd, can upload them to pypi and has basic pypy support.
  dev_url: https://github.com/PyO3/maturin
  doc_url: https://www.maturin.rs/

extra:
  recipe-maintainers:
    - apcamargo
