{% set name = "maturin" %}
{% set version = "0.14.17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb4e3311e8ce707843235fbe8748a05a3ae166c3efd6d2aa335b53dfc2bd3b88

build:
  number: 2
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('rust') }}
  host:
    - pip
    - setuptools-rust
    - wheel
    - python
    - tomli >=1.1.0
  run:
    - python
    - tomli >=1.1.0

test:
  commands:
    - maturin --help

about:
  home: https://github.com/PyO3/maturin
  license: MIT
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages

extra:
  recipe-maintainers:
    - messense
    - apcamargo
    - synapticarbors
